build:
  nodes:
    my-tests:
      environment:
        php:
          version: 7.2
      override:
        - command: phpunit --coverage-clover=my-coverage-file
          coverage:
            file: my-coverage-file
            format: php-clover